name: test-and-deploy
on:
  push:
    branches:
      - main

jobs:
    test:
        name: Run application tests
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
          
          - name: Use Node.js
            uses: actions/setup-node@v3
            
          - name: Install dependencies
            run: npm ci
            
          - name: Setup Postgres
            uses: harmon758/postgresql-action@v1
            with:
                postgresql db: "nc_news_ci"
                postgresql user: "test_user"
                postgresql password: "test_password"
                
          - name: Run tests
            run: PGDATABASE=nc_news_ci PGUSER=test_user PGPASSWORD=test_password npm t

    deploy:
        name: Deploy to Render
        runs-on: ubuntu-latest
        needs: test # wait until test is successful before running this job
        steps:
          - name: Deploy to render
            run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
